# Generated by Django 5.0 on 2023-12-20 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=5000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('price', models.CharField(max_length=10)),
                ('offerPrice', models.CharField(max_length=10)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameof_syllabus1', models.CharField(blank=True, max_length=100, null=True)),
                ('syllabus_desc1', models.CharField(blank=True, max_length=1000, null=True)),
                ('video1', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('note1', models.TextField(blank=True, max_length=100000, null=True)),
                ('note11', models.TextField(blank=True, max_length=100000, null=True)),
                ('note111', models.TextField(blank=True, max_length=100000, null=True)),
                ('code1', models.TextField(blank=True, max_length=100000, null=True)),
                ('code111', models.TextField(blank=True, max_length=100000, null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='product.courses')),
            ],
        ),
    ]
