# Generated by Django 5.0 on 2023-12-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='syllabus',
            old_name='code111',
            new_name='code2',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='note11',
            new_name='code22',
        ),
        migrations.RenameField(
            model_name='syllabus',
            old_name='note111',
            new_name='code3',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_desc1',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='code33',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='note2',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='note22',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='note3',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='note33',
            field=models.TextField(blank=True, max_length=100000, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='video2',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='video3',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='video_title1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='video_title2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='syllabus',
            name='video_title3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='nameof_syllabus1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
