# Generated by Django 5.0 on 2023-12-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_code111_syllabus_code2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
