# Generated by Django 5.0 on 2023-12-29 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_syllabus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='code1',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='code2',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='code22',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='code3',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='code33',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='note1',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='note2',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='note22',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='note3',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='note33',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='video1',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='video2',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='video3',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='video_title1',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='video_title2',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='video_title3',
        ),
        migrations.CreateModel(
            name='CourseData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=200, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('code1', models.TextField(blank=True, max_length=100000, null=True)),
                ('code2', models.TextField(blank=True, max_length=100000, null=True)),
                ('code3', models.TextField(blank=True, max_length=100000, null=True)),
                ('note1', models.TextField(blank=True, max_length=100000, null=True)),
                ('note2', models.TextField(blank=True, max_length=100000, null=True)),
                ('note3', models.TextField(blank=True, max_length=100000, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.syllabus')),
            ],
        ),
    ]
