# Generated by Django 5.0 on 2023-12-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_syllabus_code1_remove_syllabus_code2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
