# Generated by Django 5.0 on 2023-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_coursedata_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedata',
            name='duration',
        ),
        migrations.AddField(
            model_name='coursedata',
            name='duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedata',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
