# Generated by Django 5.0 on 2023-12-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_courses_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedata',
            name='codeType',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
