# Generated by Django 5.0 on 2023-12-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_course_details_user_n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_details',
            name='user_n',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
