# Generated by Django 5.0 on 2023-12-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_course_details_user_n'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course_details',
            old_name='user_n',
            new_name='user',
        ),
    ]
