# Generated by Django 5.0 on 2023-12-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_user_n_course_details_user'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course_Details',
            new_name='CourseDetails',
        ),
    ]
