# Generated by Django 5.0 on 2023-12-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_course_details_coursedetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='linkind',
        ),
    ]
