# Generated by Django 5.0 on 2023-12-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipalaya', '0002_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='Company_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
        migrations.AlterField(
            model_name='students',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
