# Generated by Django 5.0 on 2023-12-28 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sipalaya', '0003_students_profile_alter_students_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
